app:
  keycloak:
    admin:
      username: admin
      password: admin
    login:
      url: http://keycloak:8080/auth/realms/secure-realm-app/protocol/openid-connect/token
    server:
      url: http://keycloak:8080/auth
    client-secret: XmoBbKIqWn3yJvmskV5wctJvypPz8a9U
    realm:
      name: secure-realm-app
    client-id: school-app
    grant-type: password
keycloak:
  use-resource-role-mappings: 'true'
  ssl-required: external
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/secure-realm-app

#app:
#  keycloak:
#    admin:
#      username: admin
#      password: admin
#    login:
#      url: http://localhost:8080/realms/secure-realm-app/protocol/openid-connect/token
#    server:
#      url: http://keycloak:8080
#    client-secret: XmoBbKIqWn3yJvmskV5wctJvypPz8a9U
#    realm:
#      name: secure-realm-app
#    client-id: school-app
#    grant-type: password
#keycloak:
#  use-resource-role-mappings: 'true'
#  ssl-required: external
#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/secure-realm-app