version: '3.7'
services:
  app:
    image: 'school-pay-api:latest'
    build:
      context: .
    ports:
      - "8500:8082"
    networks:
      - commande-api-network
    depends_on:
      - db-postgresql
      - keycloak

  db-postgresql:
    image: 'postgres:13.1-alpine'
    container_name: dbpostgresql
    restart: always
    ports:
      - "5432:5432"
    networks:
      - commande-api-network
    environment:
      POSTGRES_USER: myowner
      POSTGRES_PASSWORD: password
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    networks:
      - commande-api-network
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: xxxxxx@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  keycloak:
    image: sleighzy/keycloak
    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: dbpostgresql
      DB_DATABASE: keycloak
      DB_USER: myowner
      DB_SCHEMA: public
      DB_PASSWORD: password
    networks:
      - commande-api-network
    ports:
      - "8080:8080"
    depends_on:
      - db-postgresql
volumes:
  local_pgdata:
  pgadmin-data:
networks:
 commande-api-network: